spring:
  application:
    name: abcmsc-consumer-depart

eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8000/eureka
      defaultZone: http://localhost:8080/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
server:
  port: 8082